services:
  - type: web
    name: blockchain_wallet_backend
    env: go
    region: oregon
    plan: free
    buildCommand: "go build -o app"
    startCommand: "./app"
    envVars:
      - key: GO_VERSION
        value: 1.22
